export const CHANGE_PROPERTIES = 'object/CHANGE_PROPERTIES'

export const CHANGE_ROBOT_PATROL_LOCS = 'object/CHANGE_ROBOT_PATROL_LOCS'

export const CHANGE_SUPPLIERS = 'object/CHANGE_SUPPLIERS'

export const CHANGE_ROBOT_OBJECT_STATUS = 'object/CHANGE_ROBOT_OBJECT_STATUS'

export const CHANGE_ROBOT_OBJECT_TYPE = 'object/CHANGE_ROBOT_OBJECT_TYPE'

export const CHANGE_VIDEO_STREAM = 'object/CHANGE_VIDEO_STREAM'
